import { ECaseState } from "./EItem";

export interface ICollectionItem {
    id: string;
    imdbID: string;
    director: string[];
    actors: string[];
    writer: string[];
    country: string[];
    originalLanguage: string[];
    genre: string[];
    title: string;
    year: string;
    poster: string;
    format: string;
    caseType: string;
    resolution: string;
    acquisitionDate: Date;
    acquisitionPrice: number;
    audioLanguage: string[];
    subtitleLanguage: string[];
    edition: string;
    isFavorite: boolean;
    hasMoreThanOneDisc: boolean;
    numberDiscs: number;
    observations: string;
    personalRating: number;
    stateCase: string;
    stateDisc: string;
    stateTape: string;
    storageLocation: string;
    supplier: string;
    watched: boolean;
    addedAt: Date;
    lastWatchedDate: Date;
    availableForExchange: boolean;
    availableForSell: boolean;
    isLoaned: boolean;
    isSpecialEdition: boolean;
}